FROM centos:centos7
RUN yum install -y which wget tar unzip git make gcc bzip2 \
&& wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz \
&& tar -zxf jdk-8u161-linux-x64.tar.gz \
&& rm -rf jdk-8u161-linux-x64.tar.gz \
&& update-alternatives --install /usr/bin/java java /jdk1.8.0_161/bin/java 100 \
&& update-alternatives --install /usr/bin/javac javac /jdk1.8.0_161/bin/javac 100 \
&& wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.6.zip \
&& unzip fastqc_v0.11.6.zip \
&& rm -rf fastqc_v0.11.6.zip \
&& cd FastQC \
&& chmod 755 fastqc \
&& ln -s /FastQC/fastqc /usr/local/bin/fastqc \
&& wget https://bootstrap.pypa.io/get-pip.py \
&& python get-pip.py \
&& rm -rf get-pip.py
COPY bssh_native_app-0.9.1.0.tar.gz /bssh_native_app-0.9.1.0.tar.gz
RUN /usr/bin/pip install simplejson /bssh_native_app-0.9.1.0.tar.gz
COPY fastqc_app.py /fastqc_app.py
