FROM jjxu/base_image_dotnet
RUN wget https://raw.githubusercontent.com/Illumina/Pisces/master/binaries/5.2.7.47/Pisces_5.2.7.47.tar.gz -O Pisces_5.2.7.47.tar.gz \
    && tar zxvf Pisces_5.2.7.47.tar.gz \
    && rm Pisces_5.2.7.47.tar.gz
COPY bssh_native_app-0.9.1.0.tar.gz /bssh_native_app-0.9.1.0.tar.gz
RUN  wget https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py \
    && rm -rf get-pip.py \
    && /usr/bin/pip install simplejson /bssh_native_app-0.9.1.0.tar.gz
COPY pisces527_app.py /pisces527_app.py
